### ISSUE TITLE
tsconfig.json file in theme necessary?

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/Atlas-theme-default#104]
Hi,

I have migrated several projects to 8.15.1 and Visual Studio Code always complains about the tsconfig.json file in the theme folder. (You need to actually open the theme folder in VS Code, it only complains when the folder is expanded in the tree view.)
Is this a left-over from the build?
Can I remove it?

Thanks in advance.

With regards,

Marcel

**Comment by wegiswes** [comment]
Hi!
You can safely remove the tsconfig file indeed. It should not be in the Atlas module. 
We are currently working on making sure unnecessary files will not end up in the module anymore.

Kind regards,
