### ISSUE TITLE
Layout Atlas_Topbar scrolls the entire page rather than the dataview body

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/Atlas-theme-default#36]
Hi,

The latest Atlas_UI_Resources module has a little issue with the Atlas_Topbar layout. The scroll container is set to scroll the entire widget, rather than per region. 

As a result, a page with a dataview as topmost component will scroll the top bar and the footer as well. These should stay where they are, only the dataview body should scroll.

I changed the scroll behavior to scroll per region.

With regards,

Marcel

**Comment by wegiswes** [comment]
Hello, 

Thanks for letting us know, but the Atlas_Topbar layout doesn't have a scroll container. Do you have some steps to reproduce?

**Comment by mgroeneweg** [comment]
![image](https://user-images.githubusercontent.com/6723899/62614401-9cebf900-b90b-11e9-81c0-ef85c344dbe8.png)
This is the scroll container I changed, it was set to scroll the full widget

**Comment by wegiswes** [comment]
Ah sorry, I overlooked that one. Will be updated in next Atlas release :)
