### ISSUE TITLE
Datepicker switching to/from darkMode

### ISSUE THREAD

**Issue by StefaniPeters** [mendix/Atlas-theme-default#65]
When working with native styling on a native app, the datepicker doesn't get styled correctly if you switch from or to darkMode. The backgroundcolor doesn't get automatically switched and you need a hard reload of the app to make the changes visible. The weird thing is that the text color does get changed when switching theme:
<img src="https://user-images.githubusercontent.com/18615440/87524399-69236280-c688-11ea-981a-27867626f1bc.png" alt="drawing" width="200"/>
<img src="https://user-images.githubusercontent.com/18615440/87524405-6c1e5300-c688-11ea-9dc2-ed94ec8b222f.png" alt="drawing" width="200"/>
After hard reload:
<img src="https://user-images.githubusercontent.com/18615440/87524868-04b4d300-c689-11ea-9d40-696e51c9a174.png" alt="drawing" width="200"/>

Is there a way to style the text color?

**Comment by IIsaku** [comment]
Hi @StefaniPeters,

We have a task on our backlog to make the text color styleable as well. We will also look into removing the necessity of a hard reload to apply the dark theme.

Greetings,

Isa Isaku
