### ISSUE TITLE
Issue with Atlas UI Resources2.6.0

### ISSUE THREAD

**Issue by jorgefl0** [mendix/Atlas-theme-default#69]
I installed the Atlas UI Resources 2.6.0  module from the AppStore built on 8.11.1 and observe an issue with the client showing text **{{appicons}}** at the top left-hand corner of the page. See screenshot.
 [
<img width="1504" alt="Screen Shot 2020-07-27 at 11 37 51 AM" src="https://user-images.githubusercontent.com/5487243/88578605-acbd8b00-cffd-11ea-9701-0b0a22189638.png">
](url)

**Comment by wegiswes** [comment]
Hi Jorge, 

Thanks for letting us know. The `{{appicons}}` is part of a new feature in version 8.12 which was released today. Please make sure your mendix app is updated to 8.12.0. That should fix it for you!
