### ISSUE TITLE
Cannot change shadow effect for progress overlay/ activity indicator for android

### ISSUE THREAD

**Issue by RobertJonesFinaps** [mendix/Atlas-theme-default#74]
While attempting to style the activity indicator we discovered that it was impossible to totally remove the shadow of the box around in android. Examining the core files: _styles/native/js/core/widgets/navigation.js_ we can see in this file (and below) that only backgroundColor and shadowColor are editable props while the rest is hardcoded.

shadowColor has no effect on android and leaves us with an awkward grey box surrounding our spinner.

Is it possible to add more editable props to the core files here?

    
```
progressOverlay: {
        container: {
            // All ViewStyle properties are allowed
            backgroundColor: navigation.progressOverlay.containerBackgroundColor,
            paddingHorizontal: spacing.largest,
            paddingVertical: spacing.large,
            borderRadius: border.radius,
            elevation: 1.5,
            shadowColor: navigation.progressOverlay.shadowColor,
            shadowOpacity: 0.1,
            shadowRadius: 10,
            shadowOffset: {
                width: 0,
                height: 2,
            },
        },
}
```

**Comment by wegiswes** [comment]
Hi Robert, 

I've added some more variables. They will be included with the next release. Hopefully that suits your needs.
Feel free to make a PR if you think anything else is missing :)
